[versions]
androidx-lifecycle = "2.4.1"
androidx-wear-compose = "1.0.0-alpha16"
compose = "1.2.0-alpha03"

[libraries]
android-build-gradle = "com.android.tools.build:gradle:7.1.1"
androidx-activity-compose = "androidx.activity:activity-compose:1.4.0"
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
compose-compiler = "androidx.compose.compiler:compiler:1.2.0-alpha03"
compose-foundation = "androidx.compose.foundation:foundation:1.2.0-alpha03"
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.7"
junit = "junit:junit:4.13.2"
kotlin-gradle-plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
test-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
test-ext-junit = "androidx.test.ext:junit:1.1.3"
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-wear-compose" }

[plugins]
android = "android:7.1.1"
android-library = "android-library:7.1.1"
android-reporting = "android-reporting:7.1.1"
com-android-application = "com.android.application:7.1.1"
com-android-asset-pack = "com.android.asset-pack:7.1.1"
com-android-asset-pack-bundle = "com.android.asset-pack-bundle:7.1.1"
com-android-base = "com.android.base:7.1.1"
com-android-dynamic-feature = "com.android.dynamic-feature:7.1.1"
com-android-internal-application = "com.android.internal.application:7.1.1"
com-android-internal-asset-pack = "com.android.internal.asset-pack:7.1.1"
com-android-internal-asset-pack-bundle = "com.android.internal.asset-pack-bundle:7.1.1"
com-android-internal-dynamic-feature = "com.android.internal.dynamic-feature:7.1.1"
com-android-internal-library = "com.android.internal.library:7.1.1"
com-android-internal-reporting = "com.android.internal.reporting:7.1.1"
com-android-internal-test = "com.android.internal.test:7.1.1"
com-android-internal-version-check = "com.android.internal.version-check:7.1.1"
com-android-library = "com.android.library:7.1.1"
com-android-lint = "com.android.lint:7.1.1"
com-android-reporting = "com.android.reporting:7.1.1"
com-android-test = "com.android.test:7.1.1"
com-diffplug-spotless = "com.diffplug.spotless:6.3.0"
kotlin = "kotlin:1.6.10"
kotlin-android = "kotlin-android:1.6.10"
kotlin-android-extensions = "kotlin-android-extensions:1.6.10"
kotlin-dce-js = "kotlin-dce-js:1.6.10"
kotlin-kapt = "kotlin-kapt:1.6.10"
kotlin-multiplatform = "kotlin-multiplatform:1.6.10"
kotlin-native-cocoapods = "kotlin-native-cocoapods:1.6.10"
kotlin-native-performance = "kotlin-native-performance:1.6.10"
kotlin-parcelize = "kotlin-parcelize:1.6.10"
kotlin-platform-android = "kotlin-platform-android:1.6.10"
kotlin-platform-common = "kotlin-platform-common:1.6.10"
kotlin-platform-js = "kotlin-platform-js:1.6.10"
kotlin-platform-jvm = "kotlin-platform-jvm:1.6.10"
kotlin-scripting = "kotlin-scripting:1.6.10"
kotlin2js = "kotlin2js:1.6.10"
org-jetbrains-kotlin-android = "org.jetbrains.kotlin.android:1.6.10"
org-jetbrains-kotlin-android-extensions = "org.jetbrains.kotlin.android.extensions:1.6.10"
org-jetbrains-kotlin-js = "org.jetbrains.kotlin.js:1.6.10"
org-jetbrains-kotlin-jvm = "org.jetbrains.kotlin.jvm:1.6.10"
org-jetbrains-kotlin-kapt = "org.jetbrains.kotlin.kapt:1.6.10"
org-jetbrains-kotlin-multiplatform = "org.jetbrains.kotlin.multiplatform:1.6.10"
org-jetbrains-kotlin-multiplatform-pm20 = "org.jetbrains.kotlin.multiplatform.pm20:1.6.10"
org-jetbrains-kotlin-native-cocoapods = "org.jetbrains.kotlin.native.cocoapods:1.6.10"
org-jetbrains-kotlin-native-performance = "org.jetbrains.kotlin.native.performance:1.6.10"
org-jetbrains-kotlin-platform-android = "org.jetbrains.kotlin.platform.android:1.6.10"
org-jetbrains-kotlin-platform-common = "org.jetbrains.kotlin.platform.common:1.6.10"
org-jetbrains-kotlin-platform-js = "org.jetbrains.kotlin.platform.js:1.6.10"
org-jetbrains-kotlin-platform-jvm = "org.jetbrains.kotlin.platform.jvm:1.6.10"
org-jetbrains-kotlin-plugin-parcelize = "org.jetbrains.kotlin.plugin.parcelize:1.6.10"
org-jetbrains-kotlin-plugin-scripting = "org.jetbrains.kotlin.plugin.scripting:1.6.10"
