[versions]
android-gradle-plugin = "7.1.3"
androidx-activity = "1.4.0"
androidx-lifecycle = "2.4.1"
androidx-test = "1.4.0"
androidx-wear-compose = "1.0.0-alpha20"
androidx-wear-tiles = "1.0.1"
androidx-wear-watchface = "1.0.1"
compose = "1.2.0-alpha07"
org-jetbrains-kotlin = "1.6.10"
org-jetbrains-kotlinx = "1.6.1"
ktlint = "0.41.0"

[libraries]
android-build-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
android-desugarjdklibs = "com.android.tools:desugar_jdk_libs:1.1.5"
android-lint-gradle = "com.android.tools.lint:lint-gradle:30.1.3"
android-material = "com.google.android.material:material:1.5.0"
android-tools-lint-gradle = "com.android.tools.lint:lint-gradle:30.1.3"
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.3"
androidx-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.0.0"
androidx-core-ktx = "androidx.core:core-ktx:1.7.0"
androidx-databinding-viewbinding = "androidx.databinding:viewbinding:7.1.3"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.0.0"
androidx-fragment-ktx = "androidx.fragment:fragment-ktx:1.4.1"
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "androidx-lifecycle" }
androidx-media = "androidx.media:media:1.5.0"
androidx-wear = "androidx.wear:wear:1.2.0"
androidx-wear-watchface-complications-data-source-ktx = "androidx.wear.watchface:watchface-complications-data-source-ktx:1.0.1"
androidx-window = "androidx.window:window:1.0.0"
com-google-truth = "com.google.truth:truth:1.1.3"
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-material-ripple = { module = "androidx.compose.material:material-ripple", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.8"
junit = "junit:junit:4.13.2"
kotlin-annotation-processing-gradle = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-gradle", version.ref = "org-jetbrains-kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlin-parcelize-compiler = { module = "org.jetbrains.kotlin:kotlin-parcelize-compiler", version.ref = "org-jetbrains-kotlin" }
kotlin-parcelize-runtime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "org-jetbrains-kotlin" }
kotlin-scripting-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "org-jetbrains-kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-guava = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-guava", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "org-jetbrains-kotlinx" }
org-robolectric = "org.robolectric:robolectric:4.7.3"
playservices-auth = "com.google.android.gms:play-services-auth:20.1.0"
playservices-wearable = "com.google.android.gms:play-services-wearable:17.1.0"
test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
test-espresso-core = "androidx.test.espresso:espresso-core:3.4.0"
test-ext-junit = "androidx.test.ext:junit:1.1.3"
test-ext-junit-ktx = "androidx.test.ext:junit-ktx:1.1.3"
test-ext-truth = "androidx.test.ext:truth:1.4.0"
test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-wear-compose" }
wear-phone-interactions = "androidx.wear:wear-phone-interactions:1.1.0-alpha03"
wear-remote-interactions = "androidx.wear:wear-remote-interactions:1.0.0"
wear-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "androidx-wear-tiles" }
wear-tiles-renderer = { module = "androidx.wear.tiles:tiles-renderer", version.ref = "androidx-wear-tiles" }
wear-watchface = { module = "androidx.wear.watchface:watchface", version.ref = "androidx-wear-watchface" }
wear-watchface-client = { module = "androidx.wear.watchface:watchface-client", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-data = { module = "androidx.wear.watchface:watchface-complications-data", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-data-source = { module = "androidx.wear.watchface:watchface-complications-data-source", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-rendering = { module = "androidx.wear.watchface:watchface-complications-rendering", version.ref = "androidx-wear-watchface" }
wear-watchface-data = { module = "androidx.wear.watchface:watchface-data", version.ref = "androidx-wear-watchface" }
wear-watchface-editor = { module = "androidx.wear.watchface:watchface-editor", version.ref = "androidx-wear-watchface" }
wear-watchface-style = { module = "androidx.wear.watchface:watchface-style", version.ref = "androidx-wear-watchface" }

[plugins]
android = "android:7.1.1"
android-library = "android-library:7.1.1"
android-reporting = "android-reporting:7.1.1"
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-android-asset-pack = { id = "com.android.asset-pack", version.ref = "android-gradle-plugin" }
com-android-asset-pack-bundle = { id = "com.android.asset-pack-bundle", version.ref = "android-gradle-plugin" }
com-android-base = "com.android.base:7.1.1"
com-android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "android-gradle-plugin" }
com-android-internal-application = "com.android.internal.application:7.1.1"
com-android-internal-asset-pack = "com.android.internal.asset-pack:7.1.1"
com-android-internal-asset-pack-bundle = "com.android.internal.asset-pack-bundle:7.1.1"
com-android-internal-dynamic-feature = "com.android.internal.dynamic-feature:7.1.1"
com-android-internal-library = "com.android.internal.library:7.1.1"
com-android-internal-reporting = "com.android.internal.reporting:7.1.1"
com-android-internal-test = "com.android.internal.test:7.1.1"
com-android-internal-version-check = "com.android.internal.version-check:7.1.1"
com-android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
com-android-lint = { id = "com.android.lint", version.ref = "android-gradle-plugin" }
com-android-reporting = "com.android.reporting:7.1.1"
com-android-test = { id = "com.android.test", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.4.2"
kotlin = { id = "kotlin", version.ref = "org-jetbrains-kotlin" }
kotlin-android = { id = "kotlin-android", version.ref = "org-jetbrains-kotlin" }
kotlin-android-extensions = { id = "kotlin-android-extensions", version.ref = "org-jetbrains-kotlin" }
kotlin-dce-js = { id = "kotlin-dce-js", version.ref = "org-jetbrains-kotlin" }
kotlin-kapt = { id = "kotlin-kapt", version.ref = "org-jetbrains-kotlin" }
kotlin-multiplatform = { id = "kotlin-multiplatform", version.ref = "org-jetbrains-kotlin" }
kotlin-native-cocoapods = { id = "kotlin-native-cocoapods", version.ref = "org-jetbrains-kotlin" }
kotlin-native-performance = { id = "kotlin-native-performance", version.ref = "org-jetbrains-kotlin" }
kotlin-parcelize = { id = "kotlin-parcelize", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-android = { id = "kotlin-platform-android", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-common = { id = "kotlin-platform-common", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-js = { id = "kotlin-platform-js", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-jvm = { id = "kotlin-platform-jvm", version.ref = "org-jetbrains-kotlin" }
kotlin-scripting = { id = "kotlin-scripting", version.ref = "org-jetbrains-kotlin" }
kotlin2js = { id = "kotlin2js", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-android-extensions = { id = "org.jetbrains.kotlin.android.extensions", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-multiplatform-pm20 = { id = "org.jetbrains.kotlin.multiplatform.pm20", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-native-performance = { id = "org.jetbrains.kotlin.native.performance", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-platform-android = { id = "org.jetbrains.kotlin.platform.android", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-platform-common = { id = "org.jetbrains.kotlin.platform.common", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-platform-js = { id = "org.jetbrains.kotlin.platform.js", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-platform-jvm = { id = "org.jetbrains.kotlin.platform.jvm", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-scripting = { id = "org.jetbrains.kotlin.plugin.scripting", version.ref = "org-jetbrains-kotlin" }
