[versions]
android-gradle-plugin = "7.1.3"
androidx-activity = "1.4.0"
androidx-lifecycle = "2.4.1"
androidx-test = "1.4.0"
androidx-wear-compose = "1.0.0-alpha21"
androidx-wear-tiles = "1.0.1"
androidx-wear-watchface = "1.0.1"
compose = "1.2.0-alpha08"
ktlint = "0.41.0"
org-jetbrains-kotlin = "1.6.20"
org-jetbrains-kotlinx = "1.6.1"

[libraries]
android-lint-gradle = "com.android.tools.lint:lint-gradle:30.1.3"
android-material = "com.google.android.material:material:1.5.0"
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-core-ktx = "androidx.core:core-ktx:1.7.0"
androidx-databinding-viewbinding = "androidx.databinding:viewbinding:7.1.3"
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-wear = "androidx.wear:wear:1.2.0"
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.8"
kotlin-annotation-processing-gradle = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-gradle", version.ref = "org-jetbrains-kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
wear-watchface = { module = "androidx.wear.watchface:watchface", version.ref = "androidx-wear-watchface" }
wear-watchface-client = { module = "androidx.wear.watchface:watchface-client", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-data = { module = "androidx.wear.watchface:watchface-complications-data", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-data-source = { module = "androidx.wear.watchface:watchface-complications-data-source", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-rendering = { module = "androidx.wear.watchface:watchface-complications-rendering", version.ref = "androidx-wear-watchface" }
wear-watchface-data = { module = "androidx.wear.watchface:watchface-data", version.ref = "androidx-wear-watchface" }
wear-watchface-editor = { module = "androidx.wear.watchface:watchface-editor", version.ref = "androidx-wear-watchface" }
wear-watchface-style = { module = "androidx.wear.watchface:watchface-style", version.ref = "androidx-wear-watchface" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.4.2"
kotlin = { id = "kotlin", version.ref = "org-jetbrains-kotlin" }
kotlin-android = { id = "kotlin-android", version.ref = "org-jetbrains-kotlin" }
kotlin-android-extensions = { id = "kotlin-android-extensions", version.ref = "org-jetbrains-kotlin" }
kotlin-dce-js = { id = "kotlin-dce-js", version.ref = "org-jetbrains-kotlin" }
kotlin-kapt = { id = "kotlin-kapt", version.ref = "org-jetbrains-kotlin" }
kotlin-multiplatform = { id = "kotlin-multiplatform", version.ref = "org-jetbrains-kotlin" }
kotlin-native-cocoapods = { id = "kotlin-native-cocoapods", version.ref = "org-jetbrains-kotlin" }
kotlin-native-performance = { id = "kotlin-native-performance", version.ref = "org-jetbrains-kotlin" }
kotlin-parcelize = { id = "kotlin-parcelize", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-android = { id = "kotlin-platform-android", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-common = { id = "kotlin-platform-common", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-js = { id = "kotlin-platform-js", version.ref = "org-jetbrains-kotlin" }
kotlin-platform-jvm = { id = "kotlin-platform-jvm", version.ref = "org-jetbrains-kotlin" }
kotlin-scripting = { id = "kotlin-scripting", version.ref = "org-jetbrains-kotlin" }
kotlin2js = { id = "kotlin2js", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-android-extensions = { id = "org.jetbrains.kotlin.android.extensions", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-js = { id = "org.jetbrains.kotlin.js", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-multiplatform-pm20 = { id = "org.jetbrains.kotlin.multiplatform.pm20", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-native-performance = { id = "org.jetbrains.kotlin.native.performance", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-platform-android = { id = "org.jetbrains.kotlin.platform.android", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-platform-common = { id = "org.jetbrains.kotlin.platform.common", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-platform-js = { id = "org.jetbrains.kotlin.platform.js", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-platform-jvm = { id = "org.jetbrains.kotlin.platform.jvm", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-scripting = { id = "org.jetbrains.kotlin.plugin.scripting", version.ref = "org-jetbrains-kotlin" }
