[versions]
#android-gradle-plugin = "8.3.0-alpha17"
android-gradle-plugin = "8.2.0"
androidx-activity = "1.8.2"
androidx-benchmark = "1.2.2"
androidx-lifecycle = "2.6.2"
androidx-test = "1.6.0-alpha04"
androidx-test-espresso = "3.6.0-alpha02"
androidx-test-ext = "1.2.0-alpha02"
androidx-test-uiautomator = "2.3.0-beta01"
androidx-wear-compose = "1.1.0-rc01"
androidx-wear-tiles = "1.1.0"
androidx-wear-watchface = "1.2.0"
compose = "1.5.0-beta01"
ktlint = "0.50.0"
org-jetbrains-kotlin = "1.9.21"
org-jetbrains-kotlinx = "1.7.3"

[libraries]
android-lint-gradle = "com.android.tools.lint:lint-gradle:31.2.0"
android-material = "com.google.android.material:material:1.11.0"
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-benchmark-junit4 = { module = "androidx.benchmark:benchmark-junit4", version.ref = "androidx-benchmark" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-databinding-viewbinding = "androidx.databinding:viewbinding:8.2.0"
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-metrics-performance = "androidx.metrics:metrics-performance:1.0.0-alpha04"
androidx-splashscreen =  "androidx.core:core-splashscreen:1.0.1"
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-ext-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }
androidx-tracing-ktx = "androidx.tracing:tracing-ktx:1.2.0"
androidx-wear = "androidx.wear:wear:1.3.0"
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.11"
kotlin-annotation-processing-gradle = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-gradle", version.ref = "org-jetbrains-kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
wear-watchface = { module = "androidx.wear.watchface:watchface", version.ref = "androidx-wear-watchface" }
wear-watchface-client = { module = "androidx.wear.watchface:watchface-client", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-data = { module = "androidx.wear.watchface:watchface-complications-data", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-data-source = { module = "androidx.wear.watchface:watchface-complications-data-source", version.ref = "androidx-wear-watchface" }
wear-watchface-complications-rendering = { module = "androidx.wear.watchface:watchface-complications-rendering", version.ref = "androidx-wear-watchface" }
wear-watchface-data = { module = "androidx.wear.watchface:watchface-data", version.ref = "androidx-wear-watchface" }
wear-watchface-editor = { module = "androidx.wear.watchface:watchface-editor", version.ref = "androidx-wear-watchface" }
wear-watchface-style = { module = "androidx.wear.watchface:watchface-style", version.ref = "androidx-wear-watchface" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.23.3"
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
